import os
import sys
import pyntbci

# -- Path setup --------------------------------------------------------------

sys.path.insert(0, os.path.abspath(".."))


# -- Project information -----------------------------------------------------

project = 'PyntBCI'
copyright = '2021, Jordy Thielen'
author = pyntbci.__author__
version = pyntbci.__version__
release = pyntbci.__version__


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
needs_sphinx = "2.0"

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',  # include documentation from docstrings
    'sphinx.ext.autosummary',  # generate autodoc summaries
    'sphinx.ext.coverage',  # collect doc coverage stats
    'sphinx.ext.napoleon',  # support for numpy and google style docstrings
    'sphinx.ext.todo',  # support for to-do items
    'sphinx.ext.viewcode',  # add links to highlighted sourcecode
    'sphinx_gallery.gen_gallery',  # add example scripts
]

sphinx_gallery_conf = {
     'examples_dirs': ['../examples', '../tutorials'],   # path to your example scripts
     'gallery_dirs': ['examples', 'tutorials'],  # path to where to save gallery generated output
     'filename_pattern': "(/example_|/tutorial_|)",
}

autosummary_generate = True
autodoc_default_options = {"inherited-members": False}
autodoc_default_flags = {"inherited-members": None}

numpydoc_show_class_members = False

exclude_patterns = ["_build", "_templates"]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

source_suffix = [".rst", ".md"]

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, to-do and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
