from typing import Union

import numpy as np
from numpy.typing import NDArray

from pyntbci.utilities import encoding_matrix


def generate_impulse_response(
    fs: int,
    components: list[tuple[float, float, float]] = None,
) -> NDArray:
    """Generate a temporal response function (i.e., a VEP / impulse response kernel) as the sum of one or more
    Ricker wavelets (a biphasic bump, similar to a single-component visual evoked potential).

    Parameters
    ----------
    fs: int
        The sampling frequency in Hz.
    components: list[tuple[float, float, float]] (default: None)
        A list of (amplitude, latency, width) tuples, each in (a.u., seconds, seconds), that are summed to form the
        impulse response. If None, three component are used (-0.5, 0.075, 0.020), (1.0, 0.1, 0.05), and
        (-0.4, 0.125, 0.020), representing a prototypical VEP.

    Returns
    -------
    impulse_response: NDArray
        The impulse response of shape (n_samples,), where n_samples covers the longest component with some margin.
    """
    if components is None:
        components = [(-0.5, 0.075, 0.020), (1.0, 0.100, 0.030), (-0.4, 0.125, 0.020)]

    duration = max(latency + 3 * width for _, latency, width in components)
    time = np.arange(0, duration, 1 / fs)

    impulse_response = np.zeros(time.size)
    for amplitude, latency, width in components:
        impulse_response += (
            amplitude * (1 - ((time - latency) / width) ** 2) * np.exp(-0.5 * ((time - latency) / width) ** 2)
        )

    return impulse_response


def generate_c_vep_source(
    stimulus: NDArray,
    y: NDArray,
    n_samples: int,
    fs: int,
    impulse_response: NDArray = None,
) -> NDArray:
    """Generate a single-source c-VEP signal per trial. The c-VEP is generated by convolving a binary stimulus with
    a VEP impulse response, following the reconvolution approach used throughout PyntBCI (see rCCA in classifiers).

    Parameters
    ----------
    stimulus: NDArray
        The (single-cycle) binary stimulus of shape (n_classes, n_bits). Sampled at fs.
    y: NDArray
        The vector of ground-truth labels of shape (n_trials), i.e., the index in stimulus of the class of each
        trial.
    n_samples: int
        The number of samples per trial.
    fs: int
        The sampling frequency in Hz.
    impulse_response: NDArray (default: None)
        The impulse response of shape (n_response_samples,) to convolve the stimulus with. If None, a default
        impulse response is generated using generate_impulse_response(fs).

    Returns
    -------
    source: NDArray
        The single-source c-VEP signal of shape (n_trials, n_samples), normalized to unit standard deviation.
    """
    if impulse_response is None:
        impulse_response = generate_impulse_response(fs)

    n_classes, n_bits = stimulus.shape

    # Tile the stimulus cycle to cover the full trial length
    n_repeats = int(np.ceil(n_samples / n_bits))
    V = np.tile(stimulus, (1, n_repeats))[:, :n_samples].astype("float64")

    # Convolve the stimulus with the impulse response to obtain a template response per class
    M = encoding_matrix(V[:, np.newaxis, :], impulse_response.size)
    T = impulse_response.dot(M.transpose((1, 0, 2)).reshape((-1, n_classes * n_samples))).reshape(n_classes, n_samples)
    T /= T.std(axis=1, keepdims=True) + np.finfo("float64").eps

    return T[y, :]


def generate_mixing_matrix(
    n_channels: int,
    n_sources: int = 1,
    primary_channels: Union[int, list[int], list[list[int]]] = None,
    leakage: float = 0.3,
    channel_jitter: float = 0.2,
    random_state: Union[int, np.random.Generator] = None,
) -> NDArray:
    """Generate a mixing matrix that projects one or more sources to channel space, simulating volume conduction. A
    set of "primary" channels can be specified per source (e.g., occipital channels for a visually evoked source),
    which receive a weight of 1, while all other channels receive a smaller "leakage" weight.

    Parameters
    ----------
    n_channels: int
        The number of channels to mix into.
    n_sources: int (default: 1)
        The number of sources to mix.
    primary_channels: int | list[int] | list[list[int]] (default: None)
        The channel indexes that should receive the full-strength signal for each source. If a single int or
        list[int] is given, it is used for every source. If a list[list[int]] is given, it must have n_sources
        entries, one list of channel indexes per source. If None, all channels are treated as primary channels for
        every source (i.e., no spatial specificity).
    leakage: float (default: 0.3)
        The relative weight (with respect to a primary channel) given to non-primary channels.
    channel_jitter: float (default: 0.2)
        The relative per-channel random gain variability, as a fraction of the weight.
    random_state: int | np.random.Generator (default: None)
        A seed or numpy random number generator to draw the channel gains from. If None, a new one is used.

    Returns
    -------
    mixing_matrix: NDArray
        The mixing matrix of shape (n_sources, n_channels).
    """
    rng = np.random.default_rng(random_state)

    if primary_channels is None:
        primary_channels = [list(range(n_channels))] * n_sources
    elif isinstance(primary_channels, (int, np.integer)):
        primary_channels = [[primary_channels]] * n_sources
    elif all(isinstance(channel, (int, np.integer)) for channel in primary_channels):
        primary_channels = [list(primary_channels)] * n_sources
    assert len(primary_channels) == n_sources, "primary_channels must have one entry per source."

    mixing_matrix = np.full((n_sources, n_channels), leakage, dtype="float64")
    for i_source, channels in enumerate(primary_channels):
        mixing_matrix[i_source, channels] = 1.0
    mixing_matrix *= 1 + channel_jitter * rng.standard_normal(mixing_matrix.shape)
    mixing_matrix = np.abs(mixing_matrix)

    return mixing_matrix


def apply_mixing_matrix(
    source: NDArray,
    mixing_matrix: NDArray,
) -> NDArray:
    """Project one or more source signals to channel space using a mixing matrix.

    Parameters
    ----------
    source: NDArray
        The source signal(s) of shape (n_trials, n_samples) for a single source, or (n_trials, n_sources, n_samples)
        for multiple sources.
    mixing_matrix: NDArray
        The mixing matrix of shape (n_sources, n_channels), e.g. as generated by generate_mixing_matrix().

    Returns
    -------
    X: NDArray
        The multi-channel signal of shape (n_trials, n_channels, n_samples).
    """
    if source.ndim == 2:
        source = source[:, np.newaxis, :]
    return np.einsum("sc,tsn->tcn", mixing_matrix, source)


def generate_white_noise(
    n_trials: int,
    n_channels: int,
    n_samples: int,
    amplitude: float = 1.0,
    random_state: Union[int, np.random.Generator] = None,
) -> NDArray:
    """Generate white sensor / measurement noise, i.e., independent and identically distributed Gaussian noise per
    channel and sample. Because it is independent across channels, this noise source guarantees that data it is
    added to remains full rank across channels (see generate_noise).

    Parameters
    ----------
    n_trials: int
        The number of trials to generate.
    n_channels: int
        The number of channels to generate.
    n_samples: int
        The number of samples per trial.
    amplitude: float (default: 1.0)
        The standard deviation of the noise.
    random_state: int | np.random.Generator (default: None)
        A seed or numpy random number generator to draw the noise from. If None, a new one is used.

    Returns
    -------
    noise: NDArray
        The white noise of shape (n_trials, n_channels, n_samples).
    """
    rng = np.random.default_rng(random_state)
    return amplitude * rng.standard_normal((n_trials, n_channels, n_samples))


def generate_pink_noise(
    n_trials: int,
    n_channels: int,
    n_samples: int,
    amplitude: float = 1.0,
    exponent: float = 1.0,
    random_state: Union[int, np.random.Generator] = None,
) -> NDArray:
    """Generate 1/f (pink) noise per channel, approximating the aperiodic background spectrum of EEG. Each channel
    is generated independently by shaping the amplitude spectrum of independent white noise.

    Parameters
    ----------
    n_trials: int
        The number of trials to generate.
    n_channels: int
        The number of channels to generate.
    n_samples: int
        The number of samples per trial.
    amplitude: float (default: 1.0)
        The standard deviation of the noise.
    exponent: float (default: 1.0)
        The spectral exponent, such that the power spectral density scales with 1 / (freq ** exponent). A value of
        1.0 gives classical pink noise, 0.0 gives white noise, and 2.0 gives brown noise.
    random_state: int | np.random.Generator (default: None)
        A seed or numpy random number generator to draw the noise from. If None, a new one is used.

    Returns
    -------
    noise: NDArray
        The pink noise of shape (n_trials, n_channels, n_samples).
    """
    rng = np.random.default_rng(random_state)

    white = rng.standard_normal((n_trials, n_channels, n_samples))
    spectrum = np.fft.rfft(white, axis=2)

    freqs = np.fft.rfftfreq(n_samples)
    freqs[0] = freqs[1]  # avoid division by zero at DC, reusing the lowest non-zero frequency instead
    scale = 1 / (freqs ** (exponent / 2))
    spectrum *= scale[np.newaxis, np.newaxis, :]

    noise = np.fft.irfft(spectrum, n=n_samples, axis=2)
    noise *= amplitude / (noise.std(axis=2, keepdims=True) + np.finfo("float64").eps)

    return noise


def generate_line_noise(
    n_trials: int,
    n_channels: int,
    n_samples: int,
    fs: int,
    freq: float = 50.0,
    amplitude: float = 1.0,
    n_harmonics: int = 1,
    channel_jitter: float = 0.1,
    random_state: Union[int, np.random.Generator] = None,
) -> NDArray:
    """Generate electrical line noise (e.g., 50 Hz mains interference and its harmonics), shared (with only small
    gain variations) across channels, with a random phase per trial.

    Parameters
    ----------
    n_trials: int
        The number of trials to generate.
    n_channels: int
        The number of channels to generate.
    n_samples: int
        The number of samples per trial.
    fs: int
        The sampling frequency in Hz.
    freq: float (default: 50.0)
        The line noise frequency in Hz (50 Hz in Europe, 60 Hz in the Americas).
    amplitude: float (default: 1.0)
        The amplitude of the fundamental frequency component. Each harmonic h is scaled by amplitude / h.
    n_harmonics: int (default: 1)
        The number of harmonics to include (1 means only the fundamental frequency).
    channel_jitter: float (default: 0.1)
        The relative per-channel random gain variability, as a fraction of the amplitude.
    random_state: int | np.random.Generator (default: None)
        A seed or numpy random number generator to draw the phase and channel gains from. If None, a new one is
        used.

    Returns
    -------
    noise: NDArray
        The line noise of shape (n_trials, n_channels, n_samples).
    """
    rng = np.random.default_rng(random_state)

    time = np.arange(n_samples) / fs
    phases = 2 * np.pi * rng.random(n_trials)
    channel_gain = 1 + channel_jitter * rng.standard_normal((1, n_channels, 1))

    noise = np.zeros((n_trials, n_channels, n_samples))
    for harmonic in range(1, 1 + n_harmonics):
        component = np.sin(2 * np.pi * harmonic * freq * time[np.newaxis, :] + phases[:, np.newaxis])
        noise += (amplitude / harmonic) * component[:, np.newaxis, :] * channel_gain

    return noise


def generate_noise(
    n_trials: int,
    n_channels: int,
    n_samples: int,
    fs: int,
    white_noise: float = 1.0,
    pink_noise: float = 0.0,
    pink_exponent: float = 1.0,
    line_noise: float = 0.0,
    line_freq: float = 50.0,
    line_harmonics: int = 1,
    random_state: Union[int, np.random.Generator] = None,
) -> NDArray:
    """Generate multi-channel EEG background noise as the sum of white sensor noise, 1/f pink noise, and electrical
    line noise. White noise is always included with a strictly positive amplitude, which guarantees that channels
    are statistically independent and hence that any data this noise is added to is of full rank across channels
    (almost surely, given at least n_channels independent samples), preventing singular covariance matrices.

    Parameters
    ----------
    n_trials: int
        The number of trials to generate.
    n_channels: int
        The number of channels to generate.
    n_samples: int
        The number of samples per trial.
    fs: int
        The sampling frequency in Hz.
    white_noise: float (default: 1.0)
        The standard deviation of the white sensor noise. Must be strictly positive to guarantee full-rank data.
    pink_noise: float (default: 0.0)
        The standard deviation of the 1/f pink noise. If 0, no pink noise is added.
    pink_exponent: float (default: 1.0)
        The spectral exponent of the pink noise, see generate_pink_noise. Only used if pink_noise > 0.
    line_noise: float (default: 0.0)
        The amplitude of the electrical line noise. If 0, no line noise is added.
    line_freq: float (default: 50.0)
        The line noise frequency in Hz. Only used if line_noise > 0.
    line_harmonics: int (default: 1)
        The number of line noise harmonics to include. Only used if line_noise > 0.
    random_state: int | np.random.Generator (default: None)
        A seed or numpy random number generator to draw the noise from. If None, a new one is used.

    Returns
    -------
    noise: NDArray
        The combined noise of shape (n_trials, n_channels, n_samples).
    """
    assert white_noise > 0, "white_noise must be strictly positive to guarantee full-rank data."
    rng = np.random.default_rng(random_state)

    noise = generate_white_noise(n_trials, n_channels, n_samples, amplitude=white_noise, random_state=rng)

    if pink_noise > 0:
        noise += generate_pink_noise(
            n_trials, n_channels, n_samples, amplitude=pink_noise, exponent=pink_exponent, random_state=rng
        )

    if line_noise > 0:
        noise += generate_line_noise(
            n_trials,
            n_channels,
            n_samples,
            fs,
            freq=line_freq,
            amplitude=line_noise,
            n_harmonics=line_harmonics,
            random_state=rng,
        )

    return noise


def generate_c_vep(
    n_trials: int,
    n_channels: int,
    n_samples: int,
    fs: int,
    n_classes: int = None,
    y: NDArray = None,
    stimulus: NDArray = None,
    cycle_size: float = None,
    impulse_response: NDArray = None,
    primary_channels: Union[int, list[int]] = None,
    snr: float = 1.0,
    white_noise: float = 1.0,
    pink_noise: float = 0.0,
    line_noise: float = 0.0,
    line_freq: float = 50.0,
    line_harmonics: int = 1,
    random_state: Union[int, np.random.Generator] = None,
) -> tuple[NDArray, NDArray, NDArray]:
    """Generate a synthetic multi-channel c-VEP EEG dataset. Each trial consists of a c-VEP source signal (the
    convolution of a binary stimulus and a VEP impulse response), projected to channel space with a mixing matrix
    that is strongest at primary_channels (e.g., occipital channels), plus background noise. The result can be
    passed directly to, e.g., eCCA or rCCA in classifiers.

    Parameters
    ----------
    n_trials: int
        The number of trials to generate.
    n_channels: int
        The number of channels to generate.
    n_samples: int
        The number of samples per trial.
    fs: int
        The sampling frequency in Hz.
    n_classes: int (default: None)
        The number of classes. Required if both y and stimulus are None.
    y: NDArray (default: None)
        The vector of ground-truth labels of shape (n_trials), i.e., the index in stimulus of the class of each
        trial. If None, trials are assigned to classes as evenly and randomly as possible.
    stimulus: NDArray (default: None)
        The (single-cycle) binary stimulus of shape (n_classes, n_bits), e.g. as generated with functions from
        stimulus. Sampled at fs. If None, a random binary stimulus is generated.
    cycle_size: float (default: None)
        The duration of one stimulus cycle in seconds, used only to generate a random stimulus (i.e., only used if
        stimulus is None). If None, defaults to n_samples / fs (i.e., a single non-repeating cycle).
    impulse_response: NDArray (default: None)
        The impulse response of shape (n_response_samples,) to convolve the stimulus with, see
        generate_c_vep_source. If None, a default impulse response is generated using
        generate_impulse_response(fs).
    primary_channels: int | list[int] (default: None)
        The channel indexes at which the c-VEP is strongest (e.g., occipital channels). See generate_mixing_matrix.
        If None, all channels are equally strong.
    snr: float (default: 1.0)
        The amplitude of the (unit standard deviation, channel-weighted) c-VEP signal relative to the noise.
    white_noise: float (default: 1.0)
        The standard deviation of the white sensor noise. See generate_noise.
    pink_noise: float (default: 0.0)
        The standard deviation of the 1/f pink noise. See generate_noise.
    line_noise: float (default: 0.0)
        The amplitude of the electrical line noise. See generate_noise.
    line_freq: float (default: 50.0)
        The line noise frequency in Hz. See generate_noise.
    line_harmonics: int (default: 1)
        The number of line noise harmonics to include. See generate_noise.
    random_state: int | np.random.Generator (default: None)
        A seed or numpy random number generator to draw the stimulus, labels, mixing matrix, and noise from. If
        None, a new one is used.

    Returns
    -------
    X: NDArray
        The EEG data of shape (n_trials, n_channels, n_samples).
    y: NDArray
        The vector of ground-truth labels of shape (n_trials).
    stimulus: NDArray
        The (single-cycle) binary stimulus of shape (n_classes, n_bits) that was used to generate the c-VEP.
    """
    rng = np.random.default_rng(random_state)

    assert y is not None or stimulus is not None or n_classes is not None, (
        "At least one of y, stimulus, or n_classes must be provided."
    )

    if stimulus is None:
        if n_classes is None:
            n_classes = 1 + int(y.max())
        n_bits = n_samples if cycle_size is None else int(cycle_size * fs)
        stimulus = (rng.random((n_classes, n_bits)) > 0.5).astype("float64")
    n_classes = stimulus.shape[0]

    if y is None:
        y = rng.permutation(np.tile(np.arange(n_classes), int(np.ceil(n_trials / n_classes)))[:n_trials])

    source = generate_c_vep_source(stimulus, y, n_samples, fs, impulse_response=impulse_response)

    mixing_matrix = generate_mixing_matrix(n_channels, n_sources=1, primary_channels=primary_channels, random_state=rng)
    X_signal = apply_mixing_matrix(source, mixing_matrix)

    X_noise = generate_noise(
        n_trials,
        n_channels,
        n_samples,
        fs,
        white_noise=white_noise,
        pink_noise=pink_noise,
        pink_exponent=1.0,
        line_noise=line_noise,
        line_freq=line_freq,
        line_harmonics=line_harmonics,
        random_state=rng,
    )

    X = snr * X_signal + X_noise

    return X, y, stimulus
