name: documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  docs:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          pip install .
          pip install sphinx sphinx_rtd_theme myst_parser sphinx-gallery

      - name: Sphinx build
        run: |
          cd doc/
          make html

      - name: Commit documentation changes
        run: |
          git clone https://github.com/thijor/pyntbci.git --branch gh-pages --single-branch gh-pages
          cp -r doc/_build/html/* gh-pages/
          cd gh-pages
          touch .nojekyll
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation" -a || true

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
